pipeline {
    agent any

    environment {
        AWS_REGION = 'us-east-1'
        IMAGE_NAME = 'nodeapplication'
        IMAGE_TAG = 'latest'
        AWS_CREDENTIALS_ID = '5bee2370-6a4f-4d90-a51a-52eb5632c548'
        ECR_REPO_URL = 'public.ecr.aws/s3x0y0f3'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
               script {
                    // Build Docker image
                    docker.build("${Image_NAME}:${Image_TAG}", './NodeJsApp')

                    // Run a command inside the Docker container
                    docker.image("${Image_NAME}:${Image_TAG}").inside {
                        sh "echo Hello!!"
                    }
                }
        }

        stage('Check Running Process and push to ECR') {
            steps {
                script {
                    def processName = 'server.js'
                    def isRunning = sh(script: "ps aux | grep -v grep | grep ${processName}", returnStatus: true) == 0

                    if (isRunning) {
                        echo "${processName} is running."
                        withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY', credentialsId: '5bee2370-6a4f-4d90-a51a-52eb5632c548']]) {
                        sh "aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/s3x0y0f3"
                        sh "docker tag ${IMAGE_NAME}:${IMAGE_TAG} public.ecr.aws/s3x0y0f3/nodejs-container:latest"
                        sh "docker push public.ecr.aws/s3x0y0f3/nodejs-container:latest"
                        } 


                        }
                     else {
                        error("${processName} is not running.")
                    }
                }
            }
        }
    }
    }
}


